version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: quote
    versions:
    - 1.0.8
  - dependency-name: proc-macro2
    versions:
    - 1.0.24
